CREATE DATABASE `detectorplugindb` $$

delimiter $$

CREATE TABLE `alertsbuffer` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FLD_LOGGERIDENTITY` varchar(45) DEFAULT NULL,
  `FLD_TIMESTAMP` varchar(45) DEFAULT NULL,
  `FLD_APL` double DEFAULT NULL,
  `FLD_PV` double DEFAULT NULL,
  `FLD_PX` double DEFAULT NULL,
  `FLD_PPS` double DEFAULT NULL,
  `FLD_FPS` double DEFAULT NULL,
  `FLD_DPL` double DEFAULT NULL,
  `FLD_FLOWTYPE` varchar(45) DEFAULT NULL,
  `FLD_SOURCEIP` int(11) DEFAULT NULL,
  `FLD_SOURCEPORT` int(11) DEFAULT NULL,
  `FLD_SOURCEMAC` varchar(45) DEFAULT NULL,
  `FLD_DESTINATIONIP` int(11) DEFAULT NULL,
  `FLD_DESTINATIONPORT` int(11) DEFAULT NULL,
  `FLD_DESTINATIONMAC` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
)  $$